spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: postgres
    hikari:
      schema: books
