spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaMessageTopic: "order-topic"
    kafkaMessageTopic-client: "order-status-service-topic"
    kafkaMessageGroupId: "kafka-message-group-id"
